# name: Update README

# on:
#   schedule:
#     - cron: '0 * * * *'
#   workflow_dispatch:

# jobs:
#   update-readme:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Repository
#       uses: actions/checkout@v3

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.9'

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt

#     - name: Run scraper
#       env:
#         USER: ${{ secrets.USER }}
#         EMAIL: ${{ secrets.EMAIL }}
#         PASSWORD: ${{ secrets.PASSWORD }}
#       run: python app.py

#     - name: Commit changes
#       run: |
#         git config --global user.name 'github-actions'
#         git config --global user.email 'github-actions@github.com'
#         git add README.md
#         git commit -m "Update README with latest tweets" || echo "No changes to commit"

#     - name: Push changes
#       env:
#         GH_TOKEN: ${{ secrets.GH_TOKEN }}
#       run: |
#         git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
